### Соковнин Игорь Леонидович

# Линейная алгебра

### Урок 4. Системы линейных уравнений. Часть 2

## Практическое задание

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    
__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [1]:
import numpy as np

## Задача 1

Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

__Решение__

Составим определители
$$\Delta=\begin{vmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{vmatrix}=a_{11}a_{22} - a_{12}a_{21}=
\begin{vmatrix}
1 & -2\\ 
3 & -4
\end{vmatrix}=1\cdot (-4) - 3\cdot (-2)=2.$$
$$\Delta_{1}=\begin{vmatrix}
b_{1} & a_{12}\\ 
b_{2} & a_{22}
\end{vmatrix}=b_{1}a_{22} - b_{2}a_{21}=
\begin{vmatrix}
1 & -2\\ 
7 & -4
\end{vmatrix}=1\cdot (-4) - 7\cdot (-2)=10.$$
$$\Delta_{1}=\begin{vmatrix}
a_{11} & b_{1}\\ 
a_{21} & b_{2}
\end{vmatrix}=a_{11}b_{2} - a_{21}b_{1}=
\begin{vmatrix}
1 & 1\\ 
3 & 7
\end{vmatrix}=1\cdot 7 - 3\cdot 1=4.$$

__Решение будет иметь вид__

$$x_{1}=\frac{\Delta_{1}}{\Delta}=\frac{10}{2}=5$$<br>
$$x_{2}=\frac{\Delta_{2}}{\Delta}=\frac{4}{2}=2$$

Решить систему уравнений методом Крамера:

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

Составим матрицы и найдём их определители 

In [7]:
D = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
det_D = np.linalg.det(D)
print(f'Матрица D:\n{D}')
print(f'Определитель:\n{det_D:.0f}')

Матрица D:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Определитель:
43


In [9]:
D_1 = np.array([[10, -2, 1], [1, 1, -3], [2, 4, 1]])
det_D1 = np.linalg.det(D_1)
print(f'Матрица D_1:\n{D_1}')
print(f'Определитель:\n{det_D1:.0f}')

Матрица D_1:
[[10 -2  1]
 [ 1  1 -3]
 [ 2  4  1]]
Определитель:
146


In [10]:
D_2 = np.array([[2, -1, 5], [10, -2, 1], [2, 4, 1]])
det_D2 = np.linalg.det(D_2)
print(f'Матрица D_1:\n{D_2}')
print(f'Определитель:\n{det_D2:.0f}')

Матрица D_1:
[[ 2 -1  5]
 [10 -2  1]
 [ 2  4  1]]
Определитель:
216


In [17]:
D_3 = np.array([[2, -1, 5], [1, 1, -3], [10, -2, 1]])
det_D3 = np.linalg.det(D_3)
print(f'Матрица D:\n{D_3}')
print(f'Определитель:\n{det_D3:.0f}')

Матрица D:
[[ 2 -1  5]
 [ 1  1 -3]
 [10 -2  1]]
Определитель:
-39


__Решение системы имеет вид:__

In [15]:
x_1=det_D1/det_D
x_2=det_D2/det_D
x_3=det_D3/det_D
print(f'X_1 = {x_1}')
print(f'X_2 = {x_2}')
print(f'X_3 = {x_3}')

X_1 = 3.395348837209304
X_2 = 5.023255813953492
X_3 = -0.9069767441860468


## Задача 2*

Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   __а)__ $$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

Начнем прямой ход метода Гаусса. Для этого домножим первую строку на $2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. Затем вычтем из третьего уравнения первое, домноженное на $(3)$. В матрицу $L$ запишем $l_{31}=3$. 

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}.$$

Далее умножим вторую строку на $(4)$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $4$.

В итоге получим

$$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\\ 
0 & 0 & 2
\end{pmatrix},$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}.$$

    
__б)__ $$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

Начнем прямой ход метода Гаусса. Для этого домножим первую строку на $2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. Затем вычтем из третьего уравнения первое, домноженное на $(3)$. В матрицу $L$ запишем $l_{31}=3$. Затем вычтем из четвёртого уравнения первое, домноженное на $(4)$. В матрицу $L$ запишем $l_{31}=4$. 

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
0 & 18 & 45 & 27 
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & l_{32} & 1 & 0 \\
4 & l_{42} & l_{43} & 1 
\end{pmatrix}.$$

Далее умножим вторую строку на $(5)$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $5$.
Затем вычтем из четвёртой строки вторую, домноженную на $(6)$. В матрицу $L$ запишем $l_{41}=6$. 

В итоге получим

$$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 27 & 21 
\end{pmatrix},$$

$$L=\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & l_{43} & 1 
\end{pmatrix}.$$

Далее умножим третью строку на $(9)$ и вычтем ее из четвёртой. При этом в матрицу $L$ на место $l_{43}$ запишем $9$.


В итоге получим

$$U=\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 0 & 12 
\end{pmatrix},$$

$$L=\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 9 & 1 
\end{pmatrix}.$$

## Задача 3*

Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$


Матрица коэффициентов $A$ будет иметь вид

$$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}.$$

Начнем прямой ход метода Гаусса. Для этого домножим первую строку на $11/2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $11/2$. Затем вычтем из третьего уравнения первое, домноженное на $(9/2)$. В матрицу $L$ запишем $l_{31}=9/2$. 

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 7-11/2 & 5-33/2 \\ 
0 & 8-9/2 & 4-27/2
\end{pmatrix} =
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 7/2 & -19/2
\end{pmatrix} =
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 3.5 & -9.5
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 \\ 
11/2 & 1 & 0 \\ 
9/2 & l_{32} & 1
\end{pmatrix} =
\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & l_{32} & 1
\end{pmatrix}.$$

Далее умножим вторую строку на $(7/3)$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $7/3$.

В итоге получим

$$U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 0 & -19/2+23/2\cdot 7/3 
\end{pmatrix} =
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 0 & 52/3
\end{pmatrix} = 
 =
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 3.5 & 17.333333333333332
\end{pmatrix},$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
11/2 & 1 & 0 \\ 
9/2 & 7/3 & 1
\end{pmatrix} =
\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & 2.3333333333333335 & 1
\end{pmatrix}.$$


Решим теперь систему 

$$Ly=b:$$

$$\begin{cases}
y_{1}=1, \\
11/2\cdot y_{1}+y_{2}=-6, \\
9/2\cdot y_{1}+7/3\cdot y_{2}+y_{3}=-5.
\end{cases}$$

$$y_{1}=1,$$
$$y_{2}=-23/2,$$
$$y_{3}=52/3.$$

И затем систему

$$Ux=y:$$

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
-3/2x_{2}-23/2x_{3}=-23/2, \\
52/3x_{3}=52/3.
\end{cases}=
\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
-3x_{2}-23x_{3}=-23, \\
52x_{3}=52.
\end{cases}=
\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
x_{2}=23\cdot (1 - x_{3})/3, \\
x_{3}=1.
\end{cases}$$

$$x_{3}=1$$
$$x_{2}=0,$$
$$x_{1}=-1.$$

Произведем проверку, подставив полученные значения переменных в исходную систему:

$$\begin{cases}
2\cdot (-1)+1\cdot 0+3\cdot 1= 1, \\
11\cdot (-1)+7\cdot 0+5\cdot 1= -6, \\
9\cdot (-1)+8\cdot 0+4\cdot 1= -5.
\end{cases}$$

Таким образом, найденное решение верно.

## Задача 4*

Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{\left ( -15-(-5) \cdot 5 \right )}{5}=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-(5)^2-2^2}=\sqrt{9}=3.$$

Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}=-460/5+y_1=-92+59=-33,$$

$$y_{3}=\frac{1}{3}(193-5y_1-2y_2)=\frac{(193-5\cdot{59}-2\cdot (-33))}{3}=-12.$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

$$x_{3}=-4,$$

$$x_{2}=\frac{-33-2x_3}{5}=\frac{-33+8}{5}=-5,$$

$$x_{1}=\frac{59+5x_{2}-5x_{3}}{9}=\frac{59-25+20}{9}=6.$$

Осуществим проверку, подставив полученные значения в исходную систему:


$$\begin{cases}
81\cdot 6-45(-5)+45(-4)=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Таким образом, найденное решение верно.