### Соковнин Игорь Леонидович

# Линейная алгебра

### Урок 4. Системы линейных уравнений. Часть 1

## Практическое задание

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

In [1]:
import numpy as np

## Задача 1

Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$


__Решение__

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$


Приведём матрицу к ступенчатому виду

Вычтем из второй строки первую, умноженную на 2:
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Вычтем из третьей строке первую:
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$


В итоге после преобразований мы получили матрицу треугльного вида, которая представляет следующую систему:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
~~-x_{2}+x_{3}+5x_{4}=-2, \\
~~~~~~~~~~~-2x_{3}+3x_{4}=4, \\
\end{cases}$$

Необходимо переменную x4 принять в качестве свободной переменной и через нее выразить остальные переменные.
$$x_{4}=c$$

Из 3-ой строки выражаем $x_{3}$
$$x_{3} = \frac{3}{2}c-2$$

Подставим $x_{3}$ во второе уравнение:
$$-x_{2} + \frac{3}{2}\cdot c-2 + 5\cdot с=-2\Rightarrow x_{2}=\frac{13}{2}\cdot c,$$

а затем полученные $x_{2}$ и $x_{3}$ — в первое уравнение:
$$x_{1}+\frac{13}{2}\cdot c+2-\frac{3}{2}\cdot c+2\cdot c=0\Rightarrow x_{1}=-2 - 3\cdot c.$$

Получаем решение
$$x_{1}=-2 - 3\cdot c.$$
$$x_{2}=\frac{13}{2}\cdot c,$$
$$x_{3} = \frac{3}{2}c-2,$$
$$x_{4}=c.$$

Для получения __частного решения__, приравняем переменную $x_{4}$ к 0:

$$x_{4}=0$$
$$x_{3}=-2$$
$$x_{2}=0$$
$$x_{1}=-2$$

## Теорема Кронекера — Капелли¶

Вернемся к матричному виду систем линейных уравнений 

$$Ax=b.$$

__Теорема__ 

Необходимым и достаточным условием совместности системы из $m$ уравнений с $n$ неизвестными является равенство между собой рангов матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$

$$rank A=rank \tilde A.$$

Причем:<br>
1) если $rankA=rank \tilde A=n$, где $n$ — число неизвестных, то система определена, т. е. имеет единственное решение;<br>
2) если $rankA=rank \tilde A<n$, то система имеет бесконечное количество решений;<br>
3) если $rankA<rank \tilde A$, то система несовместна.

А-матрица коэффициентов

## Задача 2

Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

Запишем матрицу A в виде

In [2]:
a = np.array([[2, -5, -3], [1, 1, -1], [3, -1, 1] ])
print(f'Матрица A:\n{a}')
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы A: {r}')

Матрица A:
[[ 2 -5 -3]
 [ 1  1 -1]
 [ 3 -1  1]]
Ранг матрицы A: 3


In [3]:
# Вектор свободный членов
b = np.array([4, -17, 0])
print(f'Вектор b: {b}')

Вектор b: [  4 -17   0]


Расширенная матрицы  A_t

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1\\ 
2 & -5 & -3\\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}.$$

In [4]:
A_t = np.array([[1, 1, -1, 0], [3, -1, 1, 4], [2, -5, -3, -17]])
print(f'Расширенная матрица A_t:\n{A_t}')
r = np.linalg.matrix_rank(A_t)
print(f'Ранг матрицы A_t: {r}')

Расширенная матрица A_t:
[[  1   1  -1   0]
 [  3  -1   1   4]
 [  2  -5  -3 -17]]
Ранг матрицы A_t: 3


Число неизвестных __n=3__

Из теоремы Кронекера — Капелли cледует, что то __система a) определена__, т. е. имеет единственное решение так как $rankA=rank \tilde A=n,  (rankA=3, rank \tilde A=3, n=3)$

б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

In [5]:
a = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9] ])
print(f'Матрица A:\n{a}')
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы A: {r}')

Матрица A:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]
Ранг матрицы A: 1


In [6]:
# Вектор свободный членов
b = np.array([1, -2, 5])
print(f'Вектор b: {b}')

Вектор b: [ 1 -2  5]


Расширенная матрицы  A_t

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
1 & -2 & 3\\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}.$$

In [7]:
A_t = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
print(f'Расширенная матрица A_t:\n{A_t}')
r = np.linalg.matrix_rank(A_t)
print(f'Ранг матрицы A_t: {r}')

Расширенная матрица A_t:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]
Ранг матрицы A_t: 2


Число неизвестных __n=3__

Из теоремы Кронекера — Капелли следует, что __система (б) несовместна__, так как $rankA<rank \tilde A, (rankA=1, rank \tilde A=2)$

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [8]:
a = np.array([[1, 2, 5], [3, 1, -8]])
print(f'Матрица A:\n{a}')
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы A: {r}')

Матрица A:
[[ 1  2  5]
 [ 3  1 -8]]
Ранг матрицы A: 2


In [9]:
# Вектор свободный членов
b = np.array([4, -2])
print(f'Вектор b: {b}')

Вектор b: [ 4 -2]


In [10]:
A_t = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
print(f'Расширенная матрица A_t:\n{A_t}')
r = np.linalg.matrix_rank(A_t)
print(f'Ранг матрицы A_t: {r}')

Расширенная матрица A_t:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]
Ранг матрицы A_t: 2


Число неизвестных __n=3__

Из теоремы Кронекера — Капелли cледует, что то __система (в) имеет бесконечное количество решений__,<br> так как $rankA=rank \tilde A<n, (rankA=2, rank \tilde A=2, n=3)$

## Задача 3

Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [11]:
a = np.array([[1, 3, -2, 4], [0, 5, 0, 0], [0, 0, 3, 0], [0, 0, 0, 2]])
print(f'Матрица A:\n{a}')
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы A: {r}')

Матрица A:
[[ 1  3 -2  4]
 [ 0  5  0  0]
 [ 0  0  3  0]
 [ 0  0  0  2]]
Ранг матрицы A: 4


In [12]:
A_t = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 0, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])

print(f'Расширенная матрица A_t:\n{A_t}')
r = np.linalg.matrix_rank(A_t)
print(f'Ранг матрицы A_t: {r}')

Расширенная матрица A_t:
[[ 1  3 -2  4  3]
 [ 0  5  0  0  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]
Ранг матрицы A_t: 4


Число неизвестных __n=4__

Из теоремы Кронекера — Капелли cледует, что то система a) определена, т. е. имеет единственное решение так как $rankA=rank \tilde A=n,  (rankA=4, rank \tilde A=4, n=4)$

## Задача 4

Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Из теоремы Кронекера — Капелли следует, что __система (б) несовместна__ тогда, когда $rankA<rank \tilde A$.

In [13]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица A:\n{A}')
r = np.linalg.matrix_rank(A)
print(f'Ранг матрицы A: {r}')

Матрица A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ранг матрицы A: 2


Следовательно, для того чтобы система была несовместной, требуется, чтобы ранг матрицы $\tilde A$ был равен 3.

 Преобразуем расширенную матрицу к ступенчатой форме

1. Умножим 1-ю строку на 2 и вычием из 2-й строки.<br>
2. Умножим 1-ю строку на 3 и вычием из 3-й строки.<br>

В результату получим матрицу
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a
\end{matrix}
\end{pmatrix}.$$

3. Умножим 2-ю строку на 2 и вычием из 3-й строки.

В результату получим матрицу
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c+a-2b
\end{matrix}
\end{pmatrix}.$$

Если , $c+a-2b \neq 0$ то система является несовместной. В противном случае одна из неизвестных является свободной переменной и, следовательно, система имеет бесконечное множество решений.